version: "3"
services:
  traefik:
    image: traefik
    restart: always
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.magento.localhost`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.docker.network=proxy1
    command:
      --api.insecure=true --providers.docker
    ports:
      - 81:80
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
networks:
  proxy:
    external:
      name: proxy